### ISSUE TITLE
Разбор параметров из комментариев

### ISSUE THREAD

**Issue by er77** [ochirom/CSCLauncher#1]
Заявка на фичу
  - в комментариях сделать разбор для предопределенных параметров 
1)  авторизация через явное указание логина и пароля, либо с помощью maxl файла 
2)  запуск maxl до и после основного скрипта 
* все что нужно вводить пользователю для успешного запуска хочется получать из комментариев 
* путь для MaxL лаунчера

**Comment by ochirom** [comment]
Done )
